---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - cleanup.quartz.metrostar.com
  resources:
  - preclusterdestroycleanups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cleanup.quartz.metrostar.com
  resources:
  - preclusterdestroycleanups/finalizers
  verbs:
  - update
- apiGroups:
  - cleanup.quartz.metrostar.com
  resources:
  - preclusterdestroycleanups/status
  verbs:
  - get
  - patch
  - update
