//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreClusterDestroyCleanup) DeepCopyInto(out *PreClusterDestroyCleanup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreClusterDestroyCleanup.
func (in *PreClusterDestroyCleanup) DeepCopy() *PreClusterDestroyCleanup {
	if in == nil {
		return nil
	}
	out := new(PreClusterDestroyCleanup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PreClusterDestroyCleanup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreClusterDestroyCleanupItem) DeepCopyInto(out *PreClusterDestroyCleanupItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreClusterDestroyCleanupItem.
func (in *PreClusterDestroyCleanupItem) DeepCopy() *PreClusterDestroyCleanupItem {
	if in == nil {
		return nil
	}
	out := new(PreClusterDestroyCleanupItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreClusterDestroyCleanupList) DeepCopyInto(out *PreClusterDestroyCleanupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PreClusterDestroyCleanup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreClusterDestroyCleanupList.
func (in *PreClusterDestroyCleanupList) DeepCopy() *PreClusterDestroyCleanupList {
	if in == nil {
		return nil
	}
	out := new(PreClusterDestroyCleanupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PreClusterDestroyCleanupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreClusterDestroyCleanupSpec) DeepCopyInto(out *PreClusterDestroyCleanupSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]PreClusterDestroyCleanupItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreClusterDestroyCleanupSpec.
func (in *PreClusterDestroyCleanupSpec) DeepCopy() *PreClusterDestroyCleanupSpec {
	if in == nil {
		return nil
	}
	out := new(PreClusterDestroyCleanupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreClusterDestroyCleanupStatus) DeepCopyInto(out *PreClusterDestroyCleanupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreClusterDestroyCleanupStatus.
func (in *PreClusterDestroyCleanupStatus) DeepCopy() *PreClusterDestroyCleanupStatus {
	if in == nil {
		return nil
	}
	out := new(PreClusterDestroyCleanupStatus)
	in.DeepCopyInto(out)
	return out
}
